baseURL = "https://bilbostack.com"
defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false
[params]
    hashtag = "#Bilbostack26"
    sponsorsLink = ""
    ticketsLink = ""
    youtubeEmbedURL = "https://www.youtube.com/embed/edKZ1P5xKyk?si=v7G8EOShgi0bSPA_"
    contactEmail = "info@bilbostack.com"
    editions = [
        { year = 2012, url = "https://web.archive.org/web/20120502190422/http://bilbostack.com/" },
        { year = 2013, url = "https://web.archive.org/web/20130110075437/http://bilbostack.com/" },
        { year = 2014, url = "https://web.archive.org/web/20140205142714/http://bilbostack.com/" },
        { year = 2015, url = "https://web.archive.org/web/20150109210526/http://bilbostack.com/" },
        { year = 2016, url = "https://web.archive.org/web/20160109081707/http://bilbostack.com/" },
        { year = 2017, url = "https://web.archive.org/web/20170601095000/http://bilbostack.com/" },
        { year = 2018, url = "https://web.archive.org/web/20180129112902/http://bilbostack.com/" },
        { year = 2019, url = "https://2019.bilbostack.com/" },
        { year = 2020, url = "https://2020.bilbostack.com/" },
        { year = 2022, url = "https://2022.bilbostack.com/" },
        { year = 2023, url = "https://2023.bilbostack.com/" },
        { year = 2024, url = "https://2024.bilbostack.com/" },
        { year = 2025, url = "https://2025.bilbostack.com/" },
    ]
    socialLinks = [
        { title = "Bluesky", url = "https://bsky.app/profile/bilbostack.com" },
        { title = "X", url = "https://twitter.com/bilbostack" },
        { title = "Telegram", url = "https://t.me/bilbostack20" },
        { title = "Github", url = "https://github.com/bilbostack" },
    ]
[languages]
    [languages.es]
      disabled = false
      languageCode = 'es'
      languageName = 'ES'
      weight = 2
    [languages.en]
      disabled = false
      languageCode = 'en'
      languageName = 'EN'
      weight = 1
    [languages.eu]
      disabled = false
      languageCode = 'eu'
      languageName = 'EU'
      weight = 0
